env:
  browser: true
  es6: true
  node: true
plugins:
  - prettier
parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
globals:
  Atomics: readonly
  BigInt: readonly
  SharedArrayBuffer: readonly
  globalThis: readonly
ignorePatterns:
  - node_modules/
  - /dist/
  - /tsc-out/
  - /test262/
rules:
  array-element-newline:
    - error
    - consistent
  arrow-parens: error
  arrow-spacing: error
  brace-style:
    - error
    - 1tbs
  comma-dangle: error
  comma-spacing: error
  curly:
    - error
    - multi-line
  func-call-spacing: off
  function-call-argument-newline:
    - error
    - consistent
  indent:
    - error
    - 2
    - SwitchCase: 1
  keyword-spacing: error
  max-len:
    - error
    - code: 120
      ignoreRegExpLiterals: true
  no-alert: error
  no-console: error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces: error
  no-param-reassign:
    - error
    - props: false
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  prefer-const:
    - off # TODO re-enable
    # - destructuring: "all"
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - avoidEscape: true
  semi: error
  space-infix-ops: error
overrides:
  - files:
      - lib/duration.ts
      - lib/init.js
      - test/all.mjs
      - test/exhaust.mjs
      - test/validStrings.mjs
    rules:
      no-console: off
  - files:
      - test/*.mjs
      - test/**/*
    rules:
      no-param-reassign: off
  - files:
      - '**/*.ts'
    plugins:
      - '@typescript-eslint'
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
      project:
        - './tsconfig.json'
        - './tools/tsconfig.json'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      # TODO turn this on - it catches lots of implicit 'any's
      # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/no-empty-function': error
      '@typescript-eslint/no-empty-interface':
        - error
        - allowSingleExtends: true
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/ban-ts-comment': off
      '@typescript-eslint/no-explicit-any': off # Todo re-enable this
      '@typescript-eslint/no-unnecessary-type-assertion': error
      '@typescript-eslint/func-call-spacing': error
      prefer-const: off
